services:
  - type: web
    name: obli-backend-prod
    runtime: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.9
      - key: MY_SECRET
        sync: false  # means you set it manually in the dashboard 